finish work on hw 05
taras-kolomiiets/nodejs-homework-template pull request #4
Opened 2022-02-13 08:21 UTC by taras-kolomiiets

2022-02-13 15:37 UTC, KirillKulakow commented on controllers/auth/login.js
> +		const passCompare = bcrypt.compareSync(password, user.password);
а если юзер не найден, думаешь пароль сможешь найти в undefined?

2022-02-13 15:38 UTC, KirillKulakow commented on controllers/auth/signup.js
> +		const avatarURL = gravatar.url(email);
добавь в данный метод опцию протокола

2022-02-13 15:56 UTC, KirillKulakow commented on controllers/contacts/delete.js
> +			req.params.contactId
на данный момент любой зарегистрированный юзер может удалить любой контакт
твое приложение имеет аутентификацию и у каждого контакта есть поле ид собственника - зачем тебе эти данные?
переделать!

2022-02-13 15:58 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +		const skip = (page - 1) * limit;
учитывая тот факт что Javascript не строго типизируемый язык программирования - ты можешь получить не число в page и limit - делай проверку!
например через isNaN

2022-02-13 15:59 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +		const contact = await Contact.findById(req.params.contactId);
на данный момент любой зарегистрированный юзер может просмотреть любой контакт
твое приложение имеет аутентификацию и у каждого контакта есть поле ид собственника - зачем тебе эти данные?
переделать!

2022-02-13 16:00 UTC, KirillKulakow commented on controllers/contacts/update.js
> +		const updatedContact = await Contact.findByIdAndUpdate(
на данный момент любой зарегистрированный юзер может изменить любой контакт
твое приложение имеет аутентификацию и у каждого контакта есть поле ид собственника - зачем тебе эти данные?
переделать!

2022-02-13 16:00 UTC, KirillKulakow commented on controllers/contacts/updateFavorite.js
> +			req.params.contactId,
на данный момент любой зарегистрированный юзер может изменить любой контакт
твое приложение имеет аутентификацию и у каждого контакта есть поле ид собственника - зачем тебе эти данные?
переделать!

2022-02-13 16:01 UTC, KirillKulakow commented on controllers/users/updateAvatar.js
> +		const avatarURL = path.join("avatars", newFilename);
сделать формат ссылки такой чтобы при переходе по данной можно было получить картинку
например http://localhost:3000/public/avatars/image.jpg

2022-02-13 16:03 UTC, KirillKulakow requested changes
Need fix

2022-02-15 13:44 UTC, taras-kolomiiets commented on controllers/auth/login.js
> +		const passCompare = bcrypt.compareSync(password, user.password);
Так після цього йде перевірка: 
		if (!user || !passCompare) {
			throw new Unauthorized("Email or password is wrong");
		}

2022-02-15 13:51 UTC, taras-kolomiiets commented on controllers/auth/signup.js
> +		const avatarURL = gravatar.url(email);
Якого саме?

2022-02-15 16:08 UTC, merged